### ISSUE TITLE
Correct the implementation of the `parent` field

### ISSUE THREAD

**Issue by oeway** [bioimage-io/core-bioimage-io-python#168]
Right now it's a tuple but the spec said it's a dict.

**Comment by constantinpape** [comment]
Just to clarify @oeway, you mean the input to `build_model` [here](https://github.com/bioimage-io/core-bioimage-io-python/blob/main/bioimageio/core/build_spec/build_model.py#L476)?!

This is not really a bug here: the function signature is in general not the same as the spec in order to simplify calling it.
You can just pass parent as like this `(<MODEL-ID>, <HASH>)` and it should translate it to the correct representation int he spec. (I am using a tuple here because this is easier to validate then a dict with fixed keys).

**Comment by FynnBe** [comment]
@oeway please reopen if this needs further discussion
