### ISSUE TITLE
feature request: generate pre-filled yaml file

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/core-bioimage-io-python#209]
Would be cool to have the command line tool generate a "template" yaml file with all _mandatory_ fields included (with examples, comments and so on), like many tools do this with config files.

**Comment by constantinpape** [comment]
There is [build_spec.build_model](https://github.com/bioimage-io/core-bioimage-io-python/blob/main/bioimageio/core/build_spec/build_model.py#L515) which implements something similar:
it generates the full model config given a path to the weight file and some more metadata. It tries to give reasonable defaults for metadata that is not passed.

That's of course not quite what you ask for here, but I am not sure if generating only the yaml is so helpful as there's no guarantee that the resulting model will be valid since the user would need to copy and package all the additional files by hand.

**Comment by oeway** [comment]
We might want to document this features in the docs about contribute models.
