### ISSUE TITLE
keep interface of build_model in line with spec 

### ISSUE THREAD

**Issue by k-dominik** [bioimage-io/core-bioimage-io-python#211]
probably a nitpick, but when building a model I ran into an unexpected type for the mandatory `cite` field/argument to build_model:

https://github.com/bioimage-io/core-bioimage-io-python/blob/902262bdce60a4c905f7b4a3b5646dc9ae68122f/bioimageio/core/build_spec/build_model.py#L528

[relevant code in spec](https://github.com/bioimage-io/spec-bioimage-io/blob/4c799d91293ec4785e7bb3e2e7a1313922e43921/bioimageio/spec/model/v0_4/schema.py#L282)

the spec states that this should be a list of dicts, but the build_model expects a single dict.

Otherwise, awesome how convenient building a model now is!

**Comment by constantinpape** [comment]
Yes, I agree that the interface for `build_model` needs some clean up to keep it in line with the spec. I have some other things to fix first and then will tackle it. Will ping you once I have time to work on it for feedback.

**Comment by oeway** [comment]
I came across with this one too, the cite field for build_model should be a list of dict (with text, url, doi). 

Also I think there are some misunderstanding on what the citations should be like.

In the notebook example in bioimage.core, I saw:
`cite = {cite_entry.text: cite_entry.url for cite_entry in model_resource.cite}`

Which suggests that dict of url indexed by the text, and I also saw the model uploaded by @constantinpape with something like this rendered in the model info page:
 - training library [[link]](https://doi.org/10.5281/zenodo.5108853)
 - architecture [[link]](https://doi.org/10.1007/978-3-319-46723-8_49)
 - segmentation algorithm [[link]](https://doi.org/10.1038/nmeth.4151)
 - data [[link]](https://doi.org/10.1007/978-3-030-59722-1_7)


While this is not an issue by itself, the intended use of the `text` field to render something like this (instead of the type of citations such as training library): 

 - Falk, T., Mai, D., Bensch, R. et al. U-Net: deep learning for cell counting, detection, and morphometry. Nat Methods 16, 67–70 (2019). [[link]](https://doi.org/10.1038/s41592-018-0261-2)
 
So the entire document will read like a proper referenced documentation and the user won't need to click on the link to see the actual paper.

**Comment by constantinpape** [comment]
> I came across with this one too, the cite field for build_model should be a list of dict (with text, url, doi).

Yes I agree. Similar issue is true for pre/post-processing. I will have a look into this next week.



> * training library [[link]](https://doi.org/10.5281/zenodo.5108853)
> 
>     * architecture [[link]](https://doi.org/10.1007/978-3-319-46723-8_49)
> 
>     * segmentation algorithm [[link]](https://doi.org/10.1038/nmeth.4151)
> 
>     * data [[link]](https://doi.org/10.1007/978-3-030-59722-1_7)
> 
> 
> While this is not an issue by itself, the intended use of the `text` field to render something like this (instead of the type of citations such as training library):
> 
>     * Falk, T., Mai, D., Bensch, R. et al. U-Net: deep learning for cell counting, detection, and morphometry. Nat Methods 16, 67–70 (2019). [[link]](https://doi.org/10.1038/s41592-018-0261-2)

I don't see much value in writing out the full citation, but do see much value in giving context to the citations.
If you just give the bullet lists to the papers it will be very hard to understand why exactly a given paper is cited.
And users can click on links to get the exact citation info; if one uses dois these are very stable.
Anyway, that's an unrelated style issue.
