### ISSUE TITLE
Issue with build_model on macOS

### ISSUE THREAD

**Issue by uschmidt83** [bioimage-io/core-bioimage-io-python#260]
Hi, there's some issue when calling `bioimageio.core.build_spec.build_model` (from StarDist) on macOS:

https://github.com/stardist/stardist/runs/6200546270?check_suite_focus=true

**Comment by uschmidt83** [comment]
Ping

**Comment by constantinpape** [comment]
Thanks for the ping @uschmidt83. I have been moving in the last few days, so was mostly offline (or preparing lectures).
But I have more time in the next 3 days and I will take a look.

**Comment by uschmidt83** [comment]
Sure, no worries. All the best for your new job!

**Comment by FynnBe** [comment]
the solution is not yet clear to me 100%, but the problem is related to an absolute path that was resolved when loading an RDF which at some point is not relative to the RDFs root anymore..
```'
...
bioimageio/spec/shared/node_transformer.py:281: in _transform_Path
    return leaf.relative_to(self.root_path)
...
ValueError: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpz_ts__sm' does not start with 
'/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpz_ts__sm'```

from this issue https://stackoverflow.com/questions/14992834/what-does-the-private-prefix-on-an-ios-file-path-indicate I take that we maybe avoid this by resolving the root path and the path at hand... I'll try to construct a test case and then fix it with `.resolve()`...

**Comment by constantinpape** [comment]
@uschmidt83 this should be fixed now with https://github.com/bioimage-io/spec-bioimage-io/releases/tag/v0.4.5post11.
(Available on pip already, conda will take a few more hours)

**Comment by constantinpape** [comment]
Now also available on conda forge.

**Comment by uschmidt83** [comment]
Looks good, thanks!
